import Head from 'next/head';
import React from 'react'

const head = () => {
  return (
    <Head>
      <title>QuizoO</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/cerveau.png' />
    </Head>
  );
}

export default head